name: flutter_hive
description: Notes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8
  provider: ^6.0.5
  workmanager: ^0.5.1
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_native_splash: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
 

flutter_icons:
  image_path: "assets/launcher_icon/android_icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#c8bfe7"
  adaptive_icon_foreground: "assets/launcher_icon/adptative_icon.png"


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/logo_splash.png
  android: true
  ios: true


flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf